### ISSUE TITLE
use_system_registry being added?

### ISSUE THREAD

**Issue by alanj853** [nerves-project/nerves_uevent#29]
Hi,

I am just wondering are there any plans for use_system_registry being added to this application? I am currently using nerves_runtime https://github.com/nerves-project/nerves_runtime/releases/tag/v0.11.8, where I make use of this option (being set to false), but I see in https://github.com/nerves-project/nerves_runtime/releases/tag/v0.12.0 it was removed.

FYI, the reason I have it set to false is that I found it quite CPU intensive with the SystemRegistry calls between https://github.com/nerves-project/nerves_runtime/blob/v0.11.8/lib/nerves_runtime/kernel/uevent.ex#L59 and https://github.com/nerves-project/nerves_runtime/blob/v0.11.8/lib/nerves_runtime/kernel/uevent.ex#L81

**Comment by fhunleth** [comment]
We have no plans to use SystemRegistry. SystemRegistry was used at one time by several people, but many of us had it turned off, like you for years.
